name: Python Build Matrix

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  python_build_matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
        version: ["3.12.1", "3.11.7", "3.10.11", "3.9.13"]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.version }}

    - name: Install APT Dependencies (Linux)
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then sudo apt update; sudo apt install libasound2-dev -y; fi
      shell: bash

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade shiv -r requirements.txt

    - name: Build Shiv Zipapp
      run: |
        shiv -c main -o frc_dashboard.pyz -r requirements.txt .

    - name: Upload Zipapp Artifact
      uses: actions/upload-artifact@v4
      with:
        name: FRC Dashboard ${{ matrix.os }} For Python v${{ matrix.version }}
        path: |
          ${{github.workspace}}/frc_dashboard.pyz
        if-no-files-found: warn
