name: Python Build Matrix

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  python_build_matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
        version: ["3.12.1", "3.11.7", "3.10.11", "3.9.13"]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.version }}

    - name: Verify Python installation
      run: |
        python --version
        which python
        python -m pip --version

    - name: Install APT Dependencies (Linux)
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then sudo apt update; sudo apt install libasound2-dev -y; fi
      shell: bash

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade shiv -r requirements.txt

    - name: Verify shiv installation
      run: |
     
