name: Build + Upload Executable Dashboard

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest  # Windows runner to build EXE

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.11'  # Change to your Python version

    - name: Verify Python installation
      run: |
        python --version
        which python
        python -m pip --version

    - name: Install APT Dependencies (Linux)
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then sudo apt update; sudo apt install libasound2-dev -y; fi
      shell: bash

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Copy Resources to Dashboard Directory
      run: |
        mkdir -p dashboard/resources
        cp ../img.png dashboard/resources/
      shell: bash

    - name: Build Shiv Zipapp
      run: |
        shiv --site-packages . -e main:main -o frc_dashboard.pyzw -r requirements.txt --compressed --verbose

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FRC Dashboard windows-latest For Python v3.10.11
        path: |
          ${{ github.workspace }}/frc_dashboard.pyzw
        if-no-files-found: warn
