name: Build EXE with PyInstaller

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest  # Windows runner to build EXE

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Change to your Python version

    - name: Verify Python installation
      run: |
        python --version
        which python
        python -m pip --version

    - name: Install APT Dependencies (Linux)
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then sudo apt update; sudo apt install libasound2-dev -y; fi
      shell: bash

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify shiv installation
      run: |
        pip show shiv
        # Check if shiv is installed properly
        if ! command -v shiv &> /dev/null
        then
          echo "shiv could not be found"
          exit 1
        else
          echo "shiv is installed"
        fi

    - name: Build Shiv Zipapp
      run: |
        shiv --site-packages dashboard -e main:main -o frc_dashboard.pyzw -r requirements.txt
        ls -l  # List files to verify if .pyz file is created
        # Print the directory content to ensure the .pyz file is in the correct path
        ls -l ${GITHUB_WORKSPACE}

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: FRC Dashboard ${{ matrix.os }} For Python v${{ matrix.version }}
        path: |
          ${{ github.workspace }}/frc_dashboard.pyzw
        if-no-files-found: warn
